### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by inteacc** [tltv/gantt-flow#5]
Hi
Can you consider including a progress bar like it was in the Vaadin 8 version (http://tomivirtanen.app.fi/gantt-demo/)?

**Comment by tltv** [comment]
This feature is added in the main branch already but release is still pending.

**Comment by tltv** [comment]
Released in 24.0.1.

Demo app [has an example](https://github.com/tltv/gantt-flow/blob/4ab422f47b52de8b3ea5cde8a2e92121593d2a7c/gantt-flow-demo/src/main/java/org/vaadin/tltv/gantt/GanttDemoView.java#L177C22-L177C39) how to add a ProgressBar that looks close to same it was in Vaadin 8 version.
