### ISSUE TITLE
Padding between bars

### ISSUE THREAD

**Issue by inteacc** [tltv/gantt-flow#6]
Hi
How can I put padding/margin between two bars as they are sticking each other as follows:
<img width="1423" alt="image" src="https://github.com/tltv/gantt-flow/assets/96451852/bf80ff6e-18da-45ab-89a0-4d085eace143">

Thanks for your help.
Mortoza

**Comment by tltv** [comment]
You can add some margin with following css:
```
gantt-element > gantt-step-element {
    margin-top: 5px;
    margin-bottom: 5px;
}
```

And to apply matching height to caption Grid, you can use this:

`grid.getStyle().set("--gantt-caption-grid-row-height", "40px");`

**Comment by inteacc** [comment]
That's awesome. Thank you for your help so promptly. It looks great!

<img width="896" alt="image" src="https://github.com/tltv/gantt-flow/assets/96451852/8368a906-49fc-4bb3-825e-ae3519bc83f3">
